services:
  codel:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - OPEN_AI_KEY=${OPEN_AI_KEY}
      - OPEN_AI_MODEL=${OPEN_AI_MODEL}
      - CODEL_BROWSER_PORT=${CODEL_BROWSER_PORT}
      - DOCKER_HOST=${DOCKER_HOST}
      - OPEN_AI_SERVER_URL=${OPEN_AI_SERVER_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp/browser:/tmp/browser
      - /mnt/cache_appdata/appdata/codel:/data
    ports:
      - "${EXTERNAL_PORT}:${PORT}"
    container_name: codel
    restart: unless-stopped
    network_mode: jakenet
